from __future__ import annotations

from .services.submission_service import submission_service

allocate_task_numbers = submission_service.allocate_task_numbers
save_file = submission_service.save_file
delete_submission_files = submission_service.delete_submission_files
create_submission = submission_service.create_submission
upsert_submission = submission_service.upsert_submission
parse_task_key = submission_service.parse_task_key
